# Generated by Django 5.2.5 on 2026-05-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="flask_user_id",
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
